---
  - block:
    - name: Curl to get influx repo key
      command: bash -c "curl -sL https://repos.influxdata.com/influxdb.key | sudo apt-key add -"
    - name: Add repo
      command: echo "deb https://repos.influxdata.com/debian stretch stable" | sudo tee /etc/apt/sources.list.d/influxdb.list

  - name: Install Telegraf
    apt:
      update_cache: yes
      name: "telegraf"
      state: "latest"

  - name: Setup Telegraf Configs
    template:
      src: "{{ item.value.src }}"
      dest: "{{ item.value.dest }}"
    with_dict: "{{ configs }}"

  - name: Start Telegraf
    service:
      name: telegraf
      state: restarted
      enabled: true
